sunknights/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'', include('sunknightsapp.urls')),
    url(r'^admin/', admin.site.urls),
]

sunknightsapp/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import logout_then_login
from django.conf import settings

from .views import views
from .views.api import roles,servers,users,user_roles,tournaments,fights,discord_roles,points_submissions,diep_tanks,mastery,quests
from rest_framework_bulk.routes import BulkRouter
from .views.oauth.views import OAuthCallbackDiscord,OAuthRedirectDiscord
from django.views.decorators.cache import cache_page

router = BulkRouter(trailing_slash=False)
router.register(r'roles',roles.RolesViewSet)
router.register(r'badgeroles',roles.SunKnightsBadgeRoleViewSet)
router.register(r'servers',servers.ServersViewSet)
router.register(r'users',users.ClanUsersViewSet)
router.register(r'usersfast',users.ClanUsersShortSet)
router.register(r'pointsinfo',users.ClanUserPointsInfoViewSet)
router.register(r'userpointssubmission', points_submissions.BasicUserPointSubmissionViewSet)
router.register(r'oneoneonefightssubmission',points_submissions.BasicFightsSubmissionViewSet)
router.register(r'managerpointsaction', points_submissions.PointsManagerActionViewSet)
router.register(r'userroles',user_roles.UserRolesViewSet)
router.register(r'tournaments',tournaments.TournamentsViewSet)
router.register(r'tournamentsfightsconnectors',tournaments.TournamentsFightsConnectorViewSet)
router.register(r'guildfights', fights.GuildFightsViewSet)
router.register(r'discord_roles',discord_roles.DiscordRolesViewSet)
router.register(r'dieptanks',diep_tanks.DiepTanksViewSet)
router.register(r'dieptanksinheritance',diep_tanks.DiepTanksInheritanceViewSet)
router.register(r'mastery',mastery.MasteriesViewSet)
router.register(r'quests',quests.QuestsViewSet,base_name="quests-api")

urlpatterns = [
    # url(r'^$', views.goodbye, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^user/(?P<id>[0-9]+)',views.user),
    url(r'^guilds',views.guilds,name='guilds'),
    url(r'^guilds/(?P<id>[0-9]+)',views.guild),
    url(r'^pointrole/(?P<id>[0-9]+)',views.pointrole),
    url(r'^leaderboard', cache_page(60)(views.leaderboard), name='leaderboard'),
    url(r'^masteries', cache_page(60*15)(views.masteries), name='masteries'),
    url(r'^aboutus', views.about_us, name='about'),
    url(r'^info/$', views.helppage, name='info'),
    url(r'^info/rules', views.helppage,{'helpstr': 'rules'}, name='rules',),
    url(r'^info/fantasydiep', views.helppage,{'helpstr': 'fantasydiep'}, name='fantasydiep',),
    url(r'^info/builds', views.helppage,{'helpstr': 'builds'}, name='builds',),
    url(r'^info/newguide', views.helppage,{'helpstr': 'newguide'}, name='newguide'),
    url(r'^info/pointguide', views.helppage,{'helpstr': 'pointguide'}, name='pointguide'),
    url(r'^info/ranks', views.helppage,{'helpstr': 'ranks'}, name='ranks'),
    url(r'^info/commands', views.helppage,{'helpstr': 'commands'}, name='commands'),
    url(r'^info/faq', views.helppage,{'helpstr': 'faq'}, name='faq'),
    url(r'^info/yt', views.helppage,{'helpstr': 'yt'}, name='yt'),
    url(r'^info/invites', views.helppage,{'helpstr': 'invites'}, name='invites'),
    url(r'^info/anokuuschool', views.helppage,{'helpstr': 'anokuuschool'}, name='anokuuschool'),
    url(r'^tankdraw', cache_page(60*15)(views.tankboard), name='tankboard'),
    url(r'^managesubmissions', views.manage_submissions, name='managesubmissions'),
    url(r'^managequests', views.manage_quests, name='managequests'),
    url(r'^api/',include(router.urls)),
    url(r'^ajaxhandler/',views.ajaxhandler, name='ajaxhandler'),
    url(r'^logout/$', views.logoutview, name='logout'),
    url(r'^accounts/login/(?P<provider>Discord)/$',
        OAuthRedirectDiscord.as_view(params={'scope': 'identify guilds'})),
    url(r'^accounts/login/(?P<provider>(\w|-)+)/$', OAuthRedirectDiscord.as_view(), name='allaccess-login'),
    url(r'^accounts/callback/(?P<provider>(\w|-)+)/$', OAuthCallbackDiscord.as_view(), name='allaccess-callback'),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

sunknightsapp/models/daily_quest.py
from django.db import models
from ..models.clan_user import ClanUser
from .diep_tank import DiepTank
from .utility.little_things import QUEST_TIER_OPTIONS

class Quest(models.Model):
    date = models.DateTimeField(auto_now_add=True,db_index=True)
    permed=models.BooleanField(default=False)



    @property
    def validtasks(self):
        return self.tasks.filter(deleted=False).order_by('points')

    def __str__(self):
                    return str(self.date)


class QuestTask(models.Model):

    quest=models.ForeignKey(Quest,related_name='tasks',on_delete=models.CASCADE)
    tier=models.PositiveSmallIntegerField(choices=QUEST_TIER_OPTIONS,default=QUEST_TIER_OPTIONS[0][0])
    questtext=models.CharField(max_length=500)
    deleted=models.BooleanField(default=False)
    manager=models.ForeignKey(ClanUser, on_delete=models.CASCADE)
    points=models.PositiveSmallIntegerField(default=0)
    cooldown=models.PositiveIntegerField(default=24)#24 hours

    @property
    def questtext_html(self):
        import markdown_deux
        return markdown_deux.markdown(self.questtext)[3:-5]




    def __str__(self):
        return self.questtext


class QuestTankMultiplier(models.Model):
    quest=models.ForeignKey(Quest,related_name='multipliers',on_delete=models.CASCADE)
    tank=models.ForeignKey(DiepTank,default=1)
    multiplier=models.DecimalField(decimal_places=2, max_digits=4, default=1)
    manager=models.ForeignKey(ClanUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.tank.name


class QuestBuild(models.Model):
    quest=models.ForeignKey(Quest,related_name='builds',on_delete=models.CASCADE)
    build=models.CharField(max_length=500)
    manager=models.ForeignKey(ClanUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.build

sunknightsapp/models/mastery.py
from django.db import models
from .diep_tank import DiepTank
from .points_info import PointsInfo, ClanUser
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from .point_submission import BasicUserPointSubmission
from ..backgroundTask.webhook_spam import mastery_unlock
from .utility.little_things import MASTERY_TIER_OPTIONS,getMasteryRankByPoints


class Mastery(models.Model):

    tank = models.ForeignKey(DiepTank, on_delete=models.CASCADE)
    pointsinfo = models.ForeignKey(PointsInfo, on_delete=models.CASCADE, related_name='masteries')
    tier = models.PositiveSmallIntegerField(choices=MASTERY_TIER_OPTIONS)
    manager = models.ForeignKey(ClanUser)
    fromSubmission = models.ForeignKey(BasicUserPointSubmission,default=None,null=True,blank=True)
    points = models.PositiveSmallIntegerField(default=0)  # will be modified after save by receiver

    def __str__(self):
        return self.tank.name

    class Meta:
        ordering = ['tank']
        unique_together = ('tank', 'pointsinfo')


        # https://web.archive.org/web/20120715042306/http://codeblogging.net/blogs/1/14


def getPointsByMasteryTier(tier:int):
    points = 0

    if tier is 1:
        points = 5
    elif tier is 2:
        points = 15
    elif tier is 3:
        points = 30
    elif tier is 4:
        points = 50
    elif tier is 5:
        points = 75

    return points



@receiver(post_save, sender=Mastery)
def update_points_on_save(sender, instance, created=False, **kwargs):
    """This is an extremly lazy (not efficient) method to always keep currentpoints up to date -
    regardless if a submission was accepted, unaccapted, created, deleted, whatever.
    A better method would be to just add/subtract points on specific actions"""

    mastery = instance
    pointsupdater(mastery.pointsinfo)





def pointsupdater(pointsinfo):  # TODO add masteries points
    sumPoints = Mastery.objects.filter(pointsinfo=pointsinfo).exclude(fromSubmission = None).aggregate(models.Sum('points'))['points__sum'] or 0.0#mastery points from google docs document should already be included in old points
    pointsinfo.masterypoints = sumPoints
    pointsinfo.save()


@receiver(post_delete, sender=Mastery)
def update_points_on_delete(sender, instance, **kwargs):
    pointsinfo = instance.pointsinfo
    pointsupdater(pointsinfo)



    # https://web.archive.org/web/20120715042306/http://codeblogging.net/blogs/1/14


@receiver(post_save, sender=BasicUserPointSubmission)
def update_submission_points_on_save(sender, instance, created=False, **kwargs):
    """This is an extremly lazy (not efficient) method to always keep currentpoints up to date -
    regardless if a submission was accepted, unaccapted, created, deleted, whatever.
    A better method would be to just add/subtract points on specific actions"""

    submission = instance
    tank = submission.tank
    tier = getMasteryRankByPoints(submission.score)
    pointsinfo = submission.pointsinfo
    manager = submission.manager

    if submission.accepted and tier > 0:  # check if another mastery can be granted

        try:
            mastery = Mastery.objects.get(tank=tank, pointsinfo=pointsinfo)
        except Mastery.DoesNotExist:
            mastery=Mastery.objects.create(tank=tank, pointsinfo=pointsinfo,points=getPointsByMasteryTier(tier), tier=tier, manager=manager,fromSubmission=submission)
            mastery_unlock(mastery)
        else:
            if not mastery.fromSubmission:
                mastery.fromSubmission = submission
                mastery.points=0
                mastery.save()
                mastery.pointsinfo.save()


        if mastery.tier < tier:
                newpoints=getPointsByMasteryTier(tier)-getPointsByMasteryTier(mastery.tier)
                mastery.points=newpoints
                mastery.manager = manager
                mastery.fromSubmission = submission
                mastery.tier = tier
                mastery.save()
                mastery_unlock(mastery)
    elif not created and not submission.accepted and submission.decided and tier>0:
        try:
            mastery = Mastery.objects.get(fromSubmission=submission)
        except Mastery.DoesNotExist:
            pass
        else:
            mastery.delete()

sunknightsapp/forms/base_form.py
from django import forms
from django.forms import ModelForm
from django.http import JsonResponse


class BaseForm(ModelForm):
    ajax_action_id = forms.IntegerField(min_value=0, widget=forms.HiddenInput(), required=True)
    id_value=0

    def __init__(self, id, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        self.fields['ajax_action_id'].widget.attrs['value'] = id.value
        self.id_value=id.value

    def handle(self, request):
        raise NotImplementedError("Please Implement this method")

    def noPermission(self):
        return self.response(False, "You do not have sufficient Permissions for this action")

    def response(self, noErrors=True, message=""):
        return JsonResponse({'status': 'success' if noErrors else 'failure', 'message': message,'action':self.id_value})

    def datatables_leaderboard_response(self,data):
        return JsonResponse(data)

    class Meta:
        fields = ('ajax_action_id',)
        pass

sunknightsapp/forms/fight_forms.py
from django import forms

from .base_form import *
from ..enums.AjaxActions import AjaxAction
from ..models.guildfight import GuildFight
from ..serializers.fight_serializer import GuildFightSerializer

sunknightsapp/forms/misc_forms.py
from .base_form import BaseForm
from  ..models.clan_user import ClanUser
from ..enums.AjaxActions import AjaxAction
class ChangeDesc(BaseForm):
  def __init__(self, *args, **kwargs):
    super(ChangeDesc, self).__init__(AjaxAction.CHANGEDESC, *args, **kwargs)

  def handle(self, request):
    try:
      newdescription=self.cleaned_data['description']
      request.user.description=newdescription
      request.user.save()
      # TODO register the stuff
    except BaseException as e:
      return self.response(False, 'Something went wrong: ' + str(e))  # TODO better exception
    else:
      return self.response(True, {'description': request.user.description})

  class Meta:
    model = ClanUser
    fields = ('description',)

sunknightsapp/forms/preferences_forms.py
##===================================## preferences_forms.py ##===================================##

##================================================================================================##
##{{{begin imports

#--
from .base_form import BaseForm
#--
from ..enums.AjaxActions import AjaxAction
#--
from ..models.clan_user import ClanUserPreferences
#--
from ..serializers.clan_user_serializer import ClanUserPreferencesSerializer
#--

##end imports}}}
##================================================================================================##

##================================================================================================##
##{{{begin class SubmitPreferencesForm:
class SavePreferencesForm(BaseForm):
    def __init__(self, *args, **kwargs):
        super(SavePreferencesForm, self).__init__(AjaxAction.SAVEPREFERENCES, *args, **kwargs)

    def handle(self, request):

        try:
            pref = ClanUserPreferences.objects.get(clan_user=request.user)
        except ClanUserPreferences.DoesNotExist:
            pref=ClanUserPreferences.objects.create(clan_user=request.user)

        pref.custom_background_enabled=self.cleaned_data['custom_background_enabled']
        pref.custom_background_url=self.cleaned_data['custom_background_url']
        pref.save()
        serializer = ClanUserPreferencesSerializer(pref)
        print(serializer.data)
        return self.response(True, {'data': (serializer.data)})

    ##============================================================================================##
    ##{{{begin class Meta:
    class Meta:
        model = ClanUserPreferences
        fields = ('custom_background_enabled', 'custom_background_url',)
    ##end class Meta}}}
    ##============================================================================================##

##end class SubmitPreferencesForm}}}
##================================================================================================##

sunknightsapp/forms/tournaments_forms.py
from django import forms

from .base_form import *
from ..enums.AjaxActions import AjaxAction
from ..models.tournament import Tournament
from ..serializers.tournament_serializer import TournamentSerializer


class RequestTournamentsForm(BaseForm):
    def __init__(self,*args, **kwargs):
        super(RequestTournamentsForm, self).__init__(AjaxAction.GETTOURNAMENTS, *args, **kwargs)


    def handle(self,request):
        try:
            tours=Tournament.objects.all()
            serializer=TournamentSerializer(tours,many=True)
        except BaseException as e:
            return self.response(False,'Something went wrong: '+str(e))
        else:

            return self.response(True,{'data':(serializer.data)})


    class Meta:
        model=Tournament
        fields=()



class CreateTournamentForm(BaseForm):
    def __init__(self,*args, **kwargs):
        super(CreateTournamentForm, self).__init__(AjaxAction.CREATETOURNAMENT, *args, **kwargs)


    def handle(self,request):
        
        if not request.user.is_war_manager:
            return self.noPermission()
            
        try:
            tour=self.save(commit=False)
            tour.creator=request.user
            tour.save()
        except:
            return self.response(False,'Something went wrong')#TODO better exception
        else:
            serializer=TournamentSerializer(tour)
            print(serializer.data)
            return self.response(True,{'data':(serializer.data)})


    class Meta:
        model=Tournament
        fields=('name','description')


class EditTournamentForm(BaseForm):
    
    
    
    pk_id=forms.IntegerField(min_value=0,widget=forms.HiddenInput(),required=True)

    def __init__(self,*args, **kwargs):
        super(EditTournamentForm, self).__init__(AjaxAction.EDITTOURNAMENT, *args, **kwargs)

    def handle(self, request):
        if not request.user.is_war_manager:
            return self.noPermission()
        try:
            tour = Tournament.objects.get(pk=int(self.cleaned_data['pk_id']))
            tour.name=self.cleaned_data['name']
            tour.description=self.cleaned_data['description']
        except BaseException as e:
            return self.response(False, 'Something went wrong: ' + str(e))  # TODO better exception

        else:

            serializer=TournamentSerializer(tour)
            return self.response(True,{'data':(serializer.data)})

    class Meta:
        model=Tournament
        fields=('pk_id','name','description')


class DeleteTournamentForm(BaseForm):
    pk_id=forms.IntegerField(min_value=0,widget=forms.HiddenInput(),required=True)

    
    def __init__(self,*args, **kwargs):
        super(DeleteTournamentForm, self).__init__(AjaxAction.DELETETOURNAMENT, *args, **kwargs)


    def handle(self,request):
        if not request.user.is_war_manager:
            return self.noPermission()
        try:
            tour=Tournament.objects.get(pk=int(self.cleaned_data['pk_id']))
            serializer = TournamentSerializer(tour)
            tour.delete()
        except BaseException as e:
            return self.response(False, 'Something went wrong: '+str(e))  # TODO better exception
        
        else:
            return self.response(True,{'data':(serializer.data)})

    class Meta:
        model=Tournament
        fields=('pk_id',)

sunknightsapp/templates/sunknightsapp/about_us.html
{% extends "sunknightsapp/base.html" %}
{% block content %}
    <div class="card-deck">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Leaders</h4>
                <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                </ul>
                </p>
            </div>
        </div>
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Admins</h4>
                <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                </ul>
                </p>
            </div>
        </div>
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Points Managers</h4>
                <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                    <li class="list-group-item"><a href="/user/{{ user.discord_id }}">{{ user.discord_nickname }}</a>
                    </li>
                </ul>
                </p>
            </div>
        </div>
    </div>


{% endblock %}

sunknightsapp/templates/sunknightsapp/guilds.html
{% extends "sunknightsapp/base.html" %}
{% block content %}
    <div class="card-group">
        <ul class="list-group">
            {% for guild in guilds %}
                <li class="list-group-item guild-card-group-item">
                    <div class="card">

                        <div class="card-block guild-card-block">
                            <h4 class="card-title">{{ guild.name }}</h4>

                            <p class="card-text guild-card-text">
                            <p>Leader: <a
                                    href="/user/{{ guild.guild_leader.discord_id }}">{{ guild.guild_leader.discord_nickname }}</a>
                            </p>
                            Members ({{ guild.members.count }}):
                            <table class="display datatables-table guilds-members-table">

                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Leaderboard Place</th>
                                    <th>Points</th>
                                    <th>Number of fought Guild wars</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for member in guild.members.all %}
                                    <tr>
                                        <td><a href="/user/{{ member.discord_id }}">{{ member.discord_nickname }}</a>
                                        </td>
                                        <td>{{ member.leaderboard_place }}</td>
                                        <td>{{ member.total_points }}</td>
                                        <td>{{ member.finished_fights.count }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            </p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}


{% block scripts %}
    $('.guilds-members-table').DataTable( {
    "order": [[ 0, "asc" ]]
    } );


{% endblock %}

sunknightsapp/templates/sunknightsapp/index.html
{% extends "sunknightsapp/base.html" %}
{% block content %}

    <div class="row">

      <body background="http://i.imgur.com/asiql8E.png"> </body>

        <div class="col-sm-6 offset-sm-3">
            {% if errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                    {% for error in errors %}
                    <li>    <p>{{ error }}</p></li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div id="card-sk-description" class="card sk-description">
                <div class="card-block">
                    <h4 class="card-title">Sun Knights</h4>
                    <p class="card-text">
                        Sun Knights is a competitive clan based on the <a href="http://diep.io">diep.io</a> game. Join us to
                        enhance
                        your
                        skills,
                        play with experienced players, take part in events, complete daily quests and unravel the gamer
                        in you!
                    </p>
                    <div class="discord-lini">
                        <div class="discord-widget"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

sunknightsapp/templates/sunknightsapp/info.html
{% extends "sunknightsapp/base.html" %}
{% block content %}

    <strong>Information</strong>
    <br />Links:<br />
    <ul class="squareul">
        <li><a href="{% url 'rules' %}">Rules</a></li>
        <li><a href="{% url 'fantasydiep' %}">Fantasy Diep</a></li>
        <li><a href="{% url 'builds' %}">Book Of Builds</a></li>
        <li><a href="{% url 'newguide' %}">New Member's Guide</a></li>
        <li><a href="{% url 'pointguide' %}">How To Earn Points</a></li>
        <li><a href="{% url 'ranks' %}">Ranks</a></li>
        <li><a href="{% url 'commands' %}">Commands</a></li>
        <li><a href="{% url 'faq' %}">FAQ</a></li>
        <li><a href="{% url 'yt' %}">Youtubers</a></li>
        <li><a href="{% url 'invites' %}">Important Invites</a></li>
    </ul>

{% endblock %}

sunknightsapp/templates/sunknightsapp/masteriesboard.html
{% extends "sunknightsapp/base.html" %}
{% block content %}
    <div class="card">
        <div class="card-block guild-card-block">

            <p class="card-text guild-card-text">
            <div class="table-responsive">
                <table class="display datatables-table masteries-table table-bordered" cellspacing="0" width="100%"
                       id="masteries-table">

                    <thead>
                    <tr>
                        <th>Tank</th>
                        <th>Tier 1</th>
                        <th>Tier 2</th>
                        <th>Tier 3</th>
                        <th>Tier 4</th>
                        <th>Tier 5</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for tank in tanks.all %}
                        <tr>
                            <td><span class="{{ tank.name|slugify }}"></span>{{ tank.name }}</td>
                            <td>
                                {% for mastery in tank.mastery_set.all %}
                                    {% if mastery.tier >= 1 %}
                                        <span class="mastery-member-span"><a
                                                href="/user/{{ mastery.pointsinfo.user.discord_id }}">{{ mastery.pointsinfo.user.discord_nickname }}</a></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for mastery in tank.mastery_set.all %}
                                    {% if mastery.tier >= 2 %}
                                        <span class="mastery-member-span"><a
                                                href="/user/{{ mastery.pointsinfo.user.discord_id }}">{{ mastery.pointsinfo.user.discord_nickname }}</a></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for mastery in tank.mastery_set.all %}
                                    {% if mastery.tier >= 3 %}
                                        <span class="mastery-member-span"><a
                                                href="/user/{{ mastery.pointsinfo.user.discord_id }}">{{ mastery.pointsinfo.user.discord_nickname }}</a></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for mastery in tank.mastery_set.all %}
                                    {% if mastery.tier >= 4 %}
                                        <span class="mastery-member-span"><a
                                                href="/user/{{ mastery.pointsinfo.user.discord_id }}">{{ mastery.pointsinfo.user.discord_nickname }}</a></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for mastery in tank.mastery_set.all %}
                                    {% if mastery.tier >= 5 %}
                                        <span class="mastery-member-span"><a
                                                href="/user/{{ mastery.pointsinfo.user.discord_id }}">{{ mastery.pointsinfo.user.discord_nickname }}</a></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </p>
        </div>
    </div>

{% endblock %}


{% block scripts %}
    $('#masteries-table').DataTable( {
    "order": [[ 0, "asc" ]],
    "paging": false,
    "columnDefs": [
    { "orderable": false, "targets": [1,2,3] }
    ],
    } );


{% endblock %}

sunknightsapp/templates/sunknightsapp/public_userview.html
{% extends "sunknightsapp/base.html" %}


{% block content %}
    {% load widget_tweaks %}

    <ul class="nav nav-tabs user-local-nav">
        <li class="nav-item active"><a href="#overview" class="nav-link" data-toggle="tab">Overview</a></li>
        <li class="nav-item"><a href="#decided-submissions" class="nav-link" data-toggle="tab">Decided Submission</a></li>
    </ul>


    <div id="userview-tab-content" class="tab-content clearfix">
        <div class="tab-pane active" id="overview">
            {% include "sunknightsapp/snippets/useroverview.html" %}
        </div>
        <div class="tab-pane" id="decided-submissions">
            {% include "sunknightsapp/snippets/decidedsubmissions.html" %}
        </div>

    </div>



{% endblock %}

{% block scriptself %}
    {% include "sunknightsapp/snippets/revertSubmissionScript.html" %}

    <script>
      $(function(){
        getDesc("#userdesc", '{{ lookuser.description|escapejs|default:"None" }}');
        var desc = $("#userdesccard");
        desc.mCustomScrollbar({
          axis: "y"
        });
        if (({{ lookuser.id }})==({{ user.id }})) {
            $("#userdescbutton").html("Edit").css("display", "block").attr("onclick", "editDesc(this, \"#userdesccancel\", \"#userdesc\")");
            $("#userdesccancel").attr("onclick", "cancelDesc(this, \"#userdescbutton\", \"#userdesc\")");
        }
      });
    </script>

{% endblock %}